### ISSUE TITLE
Add missing contributors to contributor list

### ISSUE THREAD

**Issue by sdruskat** [rse-council/researchsoftware.org#49]
Some contributors aren't in the contributor list yet, e.g., @alysbrett, @mwoodbri, @SimonHettrick, @shensicle. Create a PR to add them and let the all contributors bot do the rest.

**Comment by benvanwerkhoven** [comment]
I guess the allcontributors app/bot was adding everyone but that stopped once we moved the new github org. @sdruskat could you confirm?

**Comment by sdruskat** [comment]
Yes, had to re-install the bot in this repo.

**Comment by sdruskat** [comment]
@all-contributors please add @rowlandm for content.

**Comment by sdruskat** [comment]
https://github.com/all-contributors please add @rowlandm for content.

**Comment by sdruskat** [comment]
@all-contributors please add @rowlandm for content.

**Comment by sdruskat** [comment]
@all-contributors please add @nrmay for content.

**Comment by sdruskat** [comment]
@all-contributors please add @nrmay for content.

**Comment by sdruskat** [comment]
@all-contributors please add @milliams for content.
