### ISSUE TITLE
Move repository to new org

### ISSUE THREAD

**Issue by sdruskat** [rse-council/researchsoftware.org#66]
We decided to move this repository to another GH org: https://github.com/rse-council.

- [x] Move the contents of this repo
- [x] Set up CI and GH Pages
- [x] Set up DNS to resolve to the new instance of pages

**Comment by danielskatz** [comment]
this is done now, right?  @benvanwerkhoven @sdruskat

**Comment by sdruskat** [comment]
Yes, thanks Dan!
