### ISSUE TITLE
add jobs page

### ISSUE THREAD

**Issue by danielskatz** [rse-council/researchsoftware.org#89]
In the Feb 2022 council meeting, I volunteered to make a page that links to individual society/association jobs pages, so that each of them could link to this page for jobs that don't fall in their scope.

**Comment by danielskatz** [comment]
@sdruskat - I'm not quite sure how to do this in Jekyll - Can you provide any advice?  (or even start a PR that I could build on?)

**Comment by sdruskat** [comment]
@danielskatz - I'll start a PR providing a skeleton that you can build on.

**Comment by sdruskat** [comment]
@danielskatz - I've now added a skeleton PR now in #93.
To add content, just edit `jobs.md` in the repository root.
To preview locally, you'd need a Ruby installation and [Bundler](https://bundler.io/).
In the repo root, run

1. `bundle install` to install dependencies and
2. `bundle exec jekyll serve -w` to run the build and serve the page at `localhost:4000`.

Let me know if you have any further questions. Happy to help.

**Comment by danielskatz** [comment]
Thanks @sdruskat - Can you take a look at what's there now? (I can't ask you to review formally, since it's your PR)
