### ISSUE TITLE
Council mail addresses exposed in council.md

### ISSUE THREAD

**Issue by johanphilips** [rse-council/researchsoftware.org#95]
Our mail addresses are exposed to webrobots and crawlers at https://researchsoftware.org/council.html. Could we use javascript obfuscation or a captcha to hide the addresses? Sorry, I just saw in the source you are using an obfuscator already. But apparently these addresses are still indexed by google... e.g. https://www.google.com/search?q=%22c.wyatt%40society-rse.org%22 So it does not seem to work that well ☹️

**Comment by johanphilips** [comment]
or we could generate gifs with `echo -e "first.last@host" | convert.exe -background none -density 196 -resample 72 -unsharp 0x.5 -font "Courier" text:- -trim +repage -bordercolor white -border 0 first-last-image.gif` 🤓

**Comment by sdruskat** [comment]
Thanks, I'll have a look into this.

**Comment by knarrff** [comment]
Images are just cumbersome to use: you would have to re-type the address and couldn't use copy&paste. Also, they pose a problem regarding accessibility (unless you want to add an alt-text which would defeat the purpose).

Ideally and independently from the current issue, those addresses would also be linked using "mailto:xxx", which could be done using javascript as mentioned in the ticket.

On the other hand: I would expect there to be scripts that take any website, execute the javascript and only then parse the result for email addresses. The same goes for images: it is nowadays easy enough to do OCR on high-quality images.

**Comment by johanphilips** [comment]
Either way, if I Google my mail address the council page is the only hit so the obfuscation isn’t properly working.

Images were just an example and yes they are less user friendly. The only “safe” way is a captcha.

**Comment by knarrff** [comment]
> Either way, if I Google my mail address the council page is the only hit so the obfuscation isn’t properly working.

Then "your Google" isn't showing you the same as "mine", e.g.:

- https://www.researchgate.net/publication/349119757_Fabrication_grammars_bridging_design_and_robotics_to_control_emergent_material_expressions
- https://lirias.kuleuven.be/retrieve/534100
- https://marc.info/?l=zeromq-dev&m=146541591328157&w=2
- https://cris.vtt.fi/ws/files/24329277/T339.pdf
- https://docplayer.nl/amp/67039777-Het-bakske-zondag-maandag-dinsdag-woensdag-donderdag-beste-lezer.html

I'm sorry: it is hard to impossible to keep your own email address secret in academia.

**Comment by sdruskat** [comment]
Having thought about this, I think that

1. Most institutional emails will be available online anyway (e.g., via institutional websites), so I'm unsure that concerted obfuscation beyond what is already in place would be worth it, but more importantly
2. this is an open source project, and so whoever wants to further obfuscate their email is invited to do so via a PR.

If this is satisfactory enough for you, @johanphilips, feel free to close the issue :).

**Comment by benvanwerkhoven** [comment]
I agree with Stephan.

**Comment by sdruskat** [comment]
Thanks @johanphilips. I'll close, mainly because I don't have the time too look into captchas. Feel free to re-open if you want to take this on.
